language: scala
sudo: false
addons:
  apt:
    packages:
    - numactl
    - libnuma1
    - libnuma-dev
    - libnuma-dbg
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/ssl
  - $HOME/mongodb-linux-x86_64-2.6.12
  - $HOME/mongodb-linux-x86_64-amazon-3.2.8
scala:
- 2.11.8
- 2.10.5
jdk:
- oraclejdk8
- oraclejdk7
env:
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=default MONGO_VER=2_6
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=default MONGO_VER=3
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=ssl MONGO_VER=3
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=default MONGO_VER=2_6
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=default MONGO_VER=3
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=rs MONGO_VER=2_6
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=rs MONGO_VER=3
  - CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=ssl MONGO_VER=3
matrix:
  exclude:
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=default MONGO_VER=2_6
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=ssl MONGO_VER=3
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=default MONGO_VER=3
    - scala: 2.11.8
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=default MONGO_VER=2_6
    - scala: 2.11.8
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=ssl MONGO_VER=3
    - scala: 2.11.8
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=default MONGO_VER=3
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=default MONGO_VER=2_6
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=ssl MONGO_VER=3
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=default MONGO_VER=3
    - jdk: oraclejdk8
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=default MONGO_VER=2_6
    - jdk: oraclejdk8
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=ssl MONGO_VER=3
    - jdk: oraclejdk8
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=default MONGO_VER=3
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=rs MONGO_VER=2_6
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=rs MONGO_VER=3
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=rs MONGO_VER=2_6
    - scala: 2.10.5
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=rs MONGO_VER=3
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=rs MONGO_VER=2_6
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.3.13 MONGO_PROFILE=rs MONGO_VER=3
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=rs MONGO_VER=2_6
    - jdk: oraclejdk7
      env: CI_CATEGORY=INTEGRATION_TESTS AKKA_VERSION=2.4.8 MONGO_PROFILE=rs MONGO_VER=3
before_install:
- ./.travis_scripts/beforeInstall.sh $CI_CATEGORY $MONGO_VER $MONGO_PROFILE
script: ./.travis_scripts/retry.sh 3 ./.travis_scripts/validate.sh
after_success: ./.travis_scripts/afterSuccess.sh
